version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.3.2
    working_directory: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate -var 'client_id=$ARM_CLIENT_ID' -var 'client_secret=$ARM_CLIENT_SECRET' -var 'subscription_id=$ARM_SUBSCRIPTION_ID' -var "tenant_id=$ARM_TENANT_ID" -var "resource_group_name=$RESOURCE_GROUP_NAME" -var "working_dir=./packer/" ./packer/build.json
  build-base:
    docker:
      - image: hashicorp/packer:1.3.2
    working_directory: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Build Packer
          command: packer build -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "subscription_id=$ARM_SUBSCRIPTION_ID" -var "tenant_id=$ARM_TENANT_ID" -var "resource_group_name=$RESOURCE_GROUP_NAME" -var "working_dir=./packer/" ./packer/build.json
          no_output_timeout: 30m
  packer-cleanup:
    docker:
      - image: corystein/alpine-azure-cli-powershell
    working_directory: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: AZ CLI (version)
          command: az --version
          no_output_timeout: 30m
      - run:
          name: AZ login
          command: az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID" --subscription "$ARM_SUBSCRIPTION_ID"
      - run:
          name: Clean Up Packer
          command: pwsh -Command ./packer/image-cleanup.ps1 -SubscriptionId "$ARM_SUBSCRIPTION_ID" -ResourceGroup "$RESOURCE_GROUP_NAME" -KeepOnlyLatest -ImagePattern "$PATTERN"
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
      - packer-cleanup:
          requires:
            - validate
            - build-base
