version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.3.2
    working_directory: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate -var 'client_id=$ARM_CLIENT_ID' -var 'client_secret=$ARM_CLIENT_SECRET' -var 'subscription_id=$ARM_SUBSCRIPTION_ID' -var "tenant_id=$ARM_TENANT_ID" -var "resource_group_name=$RESOURCE_GROUP_NAME" -var "working_dir=./packer/" ./packer/build.json
  build-base:
    docker:
      - image: hashicorp/packer:1.3.2
    working_directory: $CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Build Packer
          command: packer build -var 'client_id=$ARM_CLIENT_ID' -var 'client_secret=$ARM_CLIENT_SECRET' -var 'subscription_id=$ARM_SUBSCRIPTION_ID' -var "tenant_id=$ARM_TENANT_ID" -var "resource_group_name=$RESOURCE_GROUP_NAME" -var "working_dir=./packer/" ./packer/build.json
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
